---
language: ruby
sudo: false
rvm:
  - 2.1.2
install:
  - bundle install --quiet
script:
  - rubocop -fs -D
  - bin/executable-tests-check
  - rake test:all
  - make test
  - bin/fetch-configlet
  - bin/configlet .
